version: "3.8"

services:
  benchmark:
    image: ghcr.io/leon0399/benchmarks:latest
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ./:/app
